### ISSUE TITLE
Re-enable mypy in pre-commit

### ISSUE THREAD

**Issue by havogt** [eth-cscs/eve_toolchain#51]
In #49 I disabled mypy again as there was an error I didn't know how to fix.

**Comment by DropD** [comment]
mypy was complaining about an extraneous `# type: ignore` comment introduced in #49 here: [src/eve/typing:25](https://github.com/eth-cscs/eve_toolchain/pull/49/files#diff-f7618252bb67f26b40b24196ca33156dR24)

Removing that comment should do the trick.
